// Code generated by GoVPP's binapi-generator. DO NOT EDIT.

package ping

import (
	"context"

	api "git.fd.io/govpp.git/api"
)

// RPCService defines RPC service ping.
type RPCService interface {
	MyPingPing(ctx context.Context, in *MyPingPing) (*MyPingPingReply, error)
}

type serviceClient struct {
	conn api.Connection
}

func NewServiceClient(conn api.Connection) RPCService {
	return &serviceClient{conn}
}

func (c *serviceClient) MyPingPing(ctx context.Context, in *MyPingPing) (*MyPingPingReply, error) {
	out := new(MyPingPingReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}
